server:
  port: 8081
spring:
  application:
    name: moviecatalog-api
  datasource:
    url: jdbc:h2:mem:movies_catalog
    username: sa #system administrator
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
